### ISSUE TITLE
Move to another org?

### ISSUE THREAD

**Issue by seaneking** [bedeoverend/gulp-process-inline#3]
Should this live in the simplaio org? Could move it to @bedeoverend's personal stack?

**Comment by bedeoverend** [comment]
@seaneking I'd be pro moving it back to mine. It doesn't have a lot of relevance, and I've a sneaking suspicion that Polymer is working on processing tools that will make this redundant anyway.

**Comment by seaneking** [comment]
righto make the switch (just make sure npm modules aren't buggered when doing that)
