### ISSUE TITLE
Gulp process inline should not decode entities

### ISSUE THREAD

**Issue by seaneking** [bedeoverend/gulp-process-inline#4]
Running `gulp-process-inline` on a HTML file decodes all special characters as a HTML entity. This is usually fine if the HTML file is just plain markup, but it breaks templating (for example).

AFAIK this behaviour is an opinionated default from Cheerio, and can be disabled by passing `{ decodeEntities: false }`, see https://github.com/cheeriojs/cheerio/issues/319

**Comment by seaneking** [comment]
Oh wait, looking at https://github.com/bedeoverend/gulp-process-inline/blob/master/index.js#L8 can you just pass `{ cheerio : { decodeEntities: false } }` to `gulp-process-inline` to handle this?

**Comment by seaneking** [comment]
Since Cheerio options can only be passed on `cheerio.load` or `cheerio.html` (rather than on require), how would you feel about making `opts.cheerio` an options block that is passed to those methods, rather than the cheerio instance itself?

**Comment by bedeoverend** [comment]
Ah good pickup! Yup happy to do this. It'll remove ability to pass your own version of Cheerio, but I don't think that's a big issue
